#! /usr/bin/env ruby

require 'pg'
require 'io/console'

 class CLI
  def initialize
    @app = ExpenseData.new
  end

  def run
    puts
    return display_help if ARGV.empty?

    command = ARGV.shift
    *options = ARGV

    error_messages = validate_commands(command, options)
    return (puts error_messages) unless error_messages.nil?

    case command
    when 'list'
      @app.list_expenses
    when 'add'
      @app.add_expense(*options)
      puts " The expense has been added."
    when 'search'
      @app.search_expenses(options.first)
    when 'delete'
      puts " The following expense has been deleted:"
      @app.delete_expense(options.first)
    when 'clear'
      confirm_answer_before_delete
    # tests ExpenseData#setup_schema
    # when 'drop'
    #   @app.drop_table
    else
      puts " Please enter a valid command."
    end
  end

  def display_help
    puts <<~MENU
      \ An expense recording system

       Commands:

         add AMOUNT MEMO  record a new expense
         clear            delete all expenses
         list             list all expenses
         delete NUMBER    remove expense with id NUMBER
         search QUERY     list expenses with a matching QUERY field (use quotations for multi-word queries)
    MENU
  end

  def validate_commands(command, options)
    case command
    when 'clear', 'list'
      ["'#{command}' does not accept any options."] unless options.empty?
    when 'add'
      [error_message_new_expense(options)]
    when 'search'
      [error_message_search(options)]
    when 'delete'
      [error_message_id(options)]
    end
  end

  def error_message_new_expense(options)
    error_messages = []

    error_messages <<
      case options.size
      when (0...2)
        " You must provide an amount and memo."
      when (3...)
        " Memos with multiple words must be wrapped with quotation marks (\" \")."
      end

    error_messages << " The amount must be entered as digits." if options.first.to_f <= 0

    error_messages
  end

  def error_message_search(query)
    case query.size
    when 0
      " You must provide a search query."
    when (2..)
      " Memos with multiple words must be wrapped with quotation marks (\" \")."
    end
  end

  def error_message_id(id)
    case id.size
    when 0
      " You must provide an id."
    when (2..)
      " You must only provide an 'id' number."
    when 1
      id = id.first.to_i

      if id <= 0
        " You must provide a positive number." 
      elsif !@app.existing_ids.include?(id.to_s)
        " There is no expense with the id '#{id}'."
      end
    end
  end

  def confirm_answer_before_delete
    loop do
      puts " This will remove all expenses.  Are you sure? (y/n)"
      response = STDIN.getch

      case response
      when 'y'
        @app.delete_all_expenses
        puts " All expenses have been deleted."
        break
      when 'n'
        break
      else
        puts " '#{response}' is not valid command."
      end
    end
  end
end

 class ExpenseData
  def initialize
    @connection = PG.connect(dbname: 'expenses')
    setup_schema
  end

  def setup_schema
    sql =<<~SQL
      SELECT COUNT(*)
        FROM information_schema.tables
       WHERE table_schema = 'public'
         AND table_name = 'expenses';
    SQL
    schema_count = @connection.exec(sql).values.flatten.join.to_i

    if schema_count.zero?
      @connection.exec(File.read('schema.sql'))
    end
  end

  def list_expenses
    results = @connection.exec("SELECT * FROM expenses ORDER BY created_on;")

    display_count(results)
    display_expenses(results) if results.ntuples > 0
  end

  def add_expense(amount, memo)
    sql = "INSERT INTO expenses (amount, memo) VALUES ($1, $2);"
    @connection.exec_params(sql, [amount.to_f, memo])
  end

  def search_expenses(query)
    sql = "SELECT * FROM expenses WHERE memo ILIKE $1;"
    results = @connection.exec_params(sql, ['%' + query + '%'])

    display_count(results)
    display_expenses(results) if results.ntuples > 0
  end

  def delete_expense(id)
    sql = "SELECT * FROM expenses WHERE id = $1;"
    results = @connection.exec_params(sql, [id])
    sql = "DELETE FROM expenses WHERE id = $1;"
    @connection.exec_params(sql, [id])

    display_expenses(results)
  end

  def delete_all_expenses
    @connection.exec("DELETE FROM expenses;")
  end

  # tests ExpenseData#setup_schema
  # def drop_table
  #   @connection.exec("DROP TABLE expenses;")

  #   puts " The table has been deleted."
  # end

  def display_expenses(expenses)
    expenses.each do |record|
      id, amount, memo, date = record.values
      puts format('  %-4s | %-14s | %10s | %-s', id, date, "$#{amount}", memo)
    end

    puts ' ' + "-" * 79

    amounts = expenses.field_values('amount').map(&:to_f)
    total = format('%.2f', amounts.sum)
    puts " Total #{format('%29s', '$' + total)}"
  end

  def display_count(expenses)
    puts (case expenses.ntuples
         when 0
           " There are no expenses."
         when 1
           " There is 1 expense."
         else
           " There are #{expenses.ntuples} expenses."
         end)
  end

  def existing_ids
    @connection.exec("SELECT id FROM expenses;").values.flatten
  end
 end

# program starts
CLI.new.run

